"""Shared state for the agent graph."""

from typing import Annotated, Any, Sequence
from typing_extensions import TypedDict

from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage


class AgentState(TypedDict):
    """State shared across all agent nodes in the graph."""

    # Conversation messages (accumulated via add_messages)
    messages: Annotated[Sequence[BaseMessage], add_messages]

    # The user's initial project idea
    project_idea: str

    # The evolving project specification
    spec: str

    # List of research tasks to perform
    research_queue: list[dict[str, Any]]

    # Research results accumulated so far
    research_findings: str

    # Pending research topics generated by the Planner (for human-in-the-loop)
    pending_research: list[str]

    # Open questions for the user
    open_questions: list[str]

    # Whether the Planner has finished researching
    planning_complete: bool

    # Final compiled report
    final_report: str

    # Progress messages for display to the user
    progress_messages: list[str]

    # MCP tools loaded from servers
    mcp_tools: list[Any]

    # User's selected MCP servers to use
    selected_mcp_servers: list[str]

    # Whether the user has signed off on the final report
    report_signed_off: bool
